server:
  port: 8085

spring:
  application:
    name: fihws-spring-boot-starter
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://5876e2eb5366f.gz.cdb.myqcloud.com:15685/suibao-new?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: cdb_outerroot
#    password: Terminus123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.166.103:1433;database=appstore
    username: sa
    password: Fih123456

logging:
  config: classpath:logback-spring.xml
  path: logs/

cdgenerator:
  #文件生成默认作者
  author: xiaolong.song
  #文件输出路径
  output-dir: /Users/songxiaolong/work/IdeaProjects
  #父级包名
  parent-package: com.fih
  #是否略过视图
  skip-view: true
  copyright: Fih
  #表名称配置，多个用逗号隔开，若全部则为All。注意不同数据库大小写敏感
  tables: AdConfig